Task1
SergeyKuz1001/formal_languages_autumn_2020 pull request #1
Opened 2020-09-07 16:25 UTC by SergeyKuz1001

2020-09-08 07:32 UTC, gsvgit requested changes

2020-09-08 07:32 UTC, gsvgit commented on tests/tests_run.sh
> +for test_file in $workdir/tests/*
А почему не pytest или любая другая нормальная система для тестирования? Чтобы и в CI нормально видеть статистику и что пошло не так, и сами тесты оформлять было проще?

2020-09-09 16:00 UTC, SergeyKuz1001 commented on tests/tests_run.sh
> +for test_file in $workdir/tests/*
Не использовал pytest изначально так как не знал о существовании такой библиотеки. Переписал тестирование. Но, к сожалению, пока не смог разобраться, как тестировать с помощью pytest одну и ту же функцию с различными входными данными так, как у меня было изначально.

2020-09-09 16:44 UTC, gsvgit commented
Самое простое, наверное,
https://docs.pytest.org/en/stable/parametrize.html#pytest-mark-parametrize-parametrizing-test-functions
но вообще почитайте, есть и другие возможности, каждая со своими плюшками и
проблемами.

On Wed, Sep 9, 2020, 7:01 PM Kuzivanov Sergey <notifications@github.com>
wrote:

> *@SergeyKuz1001* commented on this pull request.
> ------------------------------
>
> In tests/tests_run.sh
> <https://github.com/SergeyKuz1001/formal_languages_autumn_2020/pull/1#discussion_r485726078>
> :
>
> > +#
>
> +#  Licensed under the Apache License, Version 2.0 (the "License");
>
> +#  you may not use this file except in compliance with the License.
>
> +#  You may obtain a copy of the License at
>
> +#
>
> +#      http://www.apache.org/licenses/LICENSE-2.0
>
> +#
>
> +#  Unless required by applicable law or agreed to in writing, software
>
> +#  distributed under the License is distributed on an "AS IS" BASIS,
>
> +#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
>
> +#  See the License for the specific language governing permissions and
>
> +#  limitations under the License.
>
> +
>
> +workdir=$1
>
> +
>
> +for test_file in $workdir/tests/*
>
>
> Не использовал pytest изначально так как не знал о существовании такой
> библиотеки. Переписал тестирование. Но, к сожалению, пока не смог
> разобраться, как тестировать с помощью pytest одну и ту же функцию с
> различными входными данными так, как у меня было изначально.
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/SergeyKuz1001/formal_languages_autumn_2020/pull/1#discussion_r485726078>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAA2CQCBLAIQ4GK7QNHCWATSE6REZANCNFSM4Q6RLPQA>
> .
>

2020-09-09 18:41 UTC, SergeyKuz1001 commented
Спасибо, прочитал, исправил

2020-09-15 05:50 UTC, gsvgit approved these changes
Ок. Но формально после дедлайна. В следующий раз будьте внимательнее.

2020-09-29 08:07 UTC, merged